spring:
  ai:
    mcp:
      server:
        # Используются настройки по умолчанию:
        # https://docs.spring.io/spring-ai/reference/1.0/api/mcp/mcp-server-boot-starter-docs.html
        stdio: false
  server:
    port: 8080

logging:
  level:
    ROOT: DEBUG
  # Требуется отключать вывод записей в консоль, т.к. их сервер будет пытаться распарсить как Json, предполагая,
  # что это запрос от клиента. Для отключения используется паттерн с пробелом, в противном случае будет показана ошибка
  # о том, что паттерн пустой.
#  pattern:
#    console: " "
  # В файл вывод происходит.
  file:
    name: ./logs/webmvc-mcp-server.log
    # Включение отладки
#    level:
#      ROOT: DEBUG