spring:
  main:
#   https://docs.spring.io/spring-boot/api/java/org/springframework/boot/WebApplicationType.html
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        # Используются настройки по умолчанию:
        # https://docs.spring.io/spring-ai/reference/1.0/api/mcp/mcp-server-boot-starter-docs.html

logging:
  level:
    ROOT: DEBUG
  # Требуется отключать вывод записей в консоль, т.к. их сервер будет пытаться распарсить как Json, предполагая,
  # что это запрос от клиента. Для отключения используется паттерн с пробелом, в противном случае будет показана ошибка
  # о том, что паттерн пустой.
  pattern:
    console: " "
  # В файл вывод происходит.
  file:
    name: ./logs/stdio-mcp-server.log
    # Включение отладки
    #  level:
#    ROOT: DEBUG