spring:
  application:
    name: example-rag-by-spring-documentation

  datasource:
    url: jdbc:postgresql://45.10.40.98:5433/ragdb
    username: raguser
    password: ragpass
    driver-class-name: org.postgresql.Driver

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:4b-it-q4_K_M

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
